### ISSUE TITLE
Webkul\Grid\Model\GridFactory not there

### ISSUE THREAD

**Issue by nuwaus** [webkulabhi/magento2-create-admin-grid-CURD-operations#1]
Webkul\Grid\Model\GridFactory  class is not exists on the repo

**Comment by webkulabhi** [comment]
The Factory class name is the name of Model class and append with the Factory word. So for example, we will have GridFactory class. You must not create this class. Magento will create it for you. Whenever Magento’s object manager encounters a class name that ends in the word ‘Factory’, it will automatically generate the Factory class in the var/generation folder if the class does not already exist. You will see the factory class in
`var/generation/<vendor_name>/<module_name>/Model/ClassFactory.php`

**Comment by urbanovich** [comment]
It doesn't work

1 exception(s):
Exception #0 (RuntimeException): Class Company\Extension\Model\GridFactory does not exist
Class Company\Extension\Controller\Adminhtml\TypeFor\AddFrameType\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only.
